name: Cloud Init Poppler SSH

on:
  workflow_dispatch:

jobs:
  setup-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl jq gnupg ca-certificates
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure with managed identity
        run: |
          az login --identity fa-gaviti-ci

      - name: Retrieve SSH private key from Key Vault
        run: |
          mkdir -p /home/runner/.ssh
          az keyvault secret show \
            --name vm-poppler-ssh-key \
            --vault-name samkvshared \
            --query value \
            -o tsv > /home/runner/.ssh/poppler_key.pem

      - name: Set permissions on SSH key
        run: |
          chmod 600 /home/runner/.ssh/poppler_key.pem

      - name: SSH key retrieved and secured
        run: echo "SSH key retrieved and secured"
