name: Deploy Function App

on:
  push:
    branches:
      - main
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - slot: production
            branch: main
            env: prod
          - slot: uat
            branch: uat
            env: uat

    if: github.ref == format('refs/heads/{0}', matrix.branch)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Functions (production)
        if: matrix.slot == 'production'
        uses: Azure/functions-action@v1
        with:
          app-name: fa-gaviti-prod
          slot-name: production
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PRODUCTION }}

      - name: Deploy to Azure Functions (uat)
        if: matrix.slot == 'uat'
        uses: Azure/functions-action@v1
        with:
          app-name: fa-gaviti-prod
          slot-name: uat
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_UAT }}