name: Deploy Azure Function App (UAT or PROD)

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment to deploy
        options:
          - uat
          - prod
        required: true

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment ZIP
      run: |
        zip -r fa-gaviti-function.zip . -x "*.git*" -x "*.venv*" -x "__pycache__/*" -x "*.bicepparam" -x "*.bicep"

    - name: Deploy via ZipDeploy to ${{ github.event.inputs.environment }}
      run: |
        curl -X POST "https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy" \
          -u "${{ secrets.AZURE_FUNCTIONAPP_USER }}:${{ secrets.AZURE_FUNCTIONAPP_PWD }}" \
          --data-binary @"fa-gaviti-function.zip" \
          -H "Content-Type: application/zip"
