name: Deploy Function App

on:
  push:
    branches:
      - main
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - slot: production
            branch: main
            env: prod
          - slot: uat
            branch: uat
            env: uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
      - name: Install dependencies
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Functions (${{ matrix.slot }})
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branch) }}
        uses: Azure/functions-action@v1
        with:
          app-name: fa-gaviti-prod
          # Use the slot name from the matrix
          slot-name: ${{ matrix.slot }}
          package: '.'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_${{ matrix.slot | upper }} }}
