name: Manual Deploy to UAT and Prod Slots

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Adjust if your code is in a subfolder
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment & install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/**"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fa-gaviti-prod
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slot: [uat, prod]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fa-gaviti-prod

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to ${{ matrix.slot }} slot
        uses: Azure/functions-action@v1
        with:
          app-name: fa-gaviti-prod
          slot-name: ${{ matrix.slot == 'prod' && 'Production' || matrix.slot }}
          publish-profile: ${{ matrix.slot == 'prod' && secrets.AZURE_PUBLISH_PROFILE_PROD || secrets.AZURE_PUBLISH_PROFILE_UAT }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
