deploy:
  runs-on: ubuntu-latest
  needs: build
  environment: ${{ github.event.inputs.environment }}

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Azure Login with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets[format('AZURE_CREDENTIALS_{0}', github.event.inputs.environment == 'prod' && 'PROD' || 'UAT')] }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ github.event.inputs.environment == 'prod' && 'fa-gaviti-prod' || 'fa-gaviti-uat' }}
        slot-name: 'Production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
