name: Build and deploy Python project to Azure Function App (UAT/PROD)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deployment Environment
        options:
          - uat
          - prod
        required: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your Azure Function code
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Functions (${{ github.event.inputs.environment }})
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ github.event.inputs.environment == 'prod' && 'fa-gaviti-prod' || 'fa-gaviti-uat' }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets[format('PUBLISH_PROFILE_{0}', github.event.inputs.environment == 'prod' && 'PROD' || 'UAT')] }}
